datacollection/urls.py
from django.urls import path

from . import views

app_name = 'datacollection'
urlpatterns = [
    path('', views.enterdata, name="enterdata"),
    path('viewdata/', views.viewdata, name="viewdata"),
]

timetracking/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('datacollection.urls')),
]

datacollection/models.py
from django.db import models

SUBJECT_CHOICES = [
    ('AnNuMa', 'Analysis und Numerik'),
    ('Algo1', 'Algorithmen und Datenstrukturen 1'),
    ('PDB', 'Programmieren von Datenbanken'),
    ('PPDC', 'Programmierparadigmen und Compilerbau'),
    ('RTKS', 'Rechnertechnologie und kombinatorische Schaltungen'),
    ('Kaggle', 'Kaggle'),
    ('edx', 'edx'),
    ('WebProgramming', 'WebProgramming')
]

class Timestamp(models.Model):
    subject = models.CharField(max_length=128, choices=SUBJECT_CHOICES)
    date = models.DateField(auto_now_add=False)
    time_spend = models.DurationField()

datacollection/forms.py
import datetime
from django import forms

from django.forms import ModelForm

from .models import Timestamp

class DateInput(forms.DateInput):
    """Makes the HTML5 Date Input usable."""

    input_type = 'date'


class TimestampForm(forms.ModelForm):
    date = forms.DateField(initial=datetime.date.today(), widget=DateInput)

    class Meta:
        model = Timestamp
        fields = [
            "subject",
            "date",
            "time_spend"
        ]
        # widgets = {"date": DateInput()}
        # initial= {"date": datetime.date.today()}

datacollection/views.py
from django.shortcuts import render, redirect
from django.db.models import Sum
from .forms import TimestampForm
from .models import Timestamp
import datetime

# Create your views here.
def enterdata(request):
    form = TimestampForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("datacollection:viewdata")
    context = {
        "form" : form,
    }

    return render(request, 'datacollection/enterdata.html', context)

def viewdata(request):
    math = Timestamp.objects.filter(subject='AnNuMa')
    algo = Timestamp.objects.filter(subject='Algo1')
    pdb = Timestamp.objects.filter(subject="PDB")
    ppdc = Timestamp.objects.filter(subject="PPDC")
    rtks = Timestamp.objects.filter(subject="RTKS")
    kaggle = Timestamp.objects.filter(subject="Kaggle")
    edx = Timestamp.objects.filter(subject="edx")
    web = Timestamp.objects.filter(subject="WebProgramming")

    subj = []
    subjects = [math, algo, pdb, ppdc, rtks, kaggle, edx, web]
    for subject in subjects:
        subj.append([t.time_spend for t in subject])

    times = []
    for s in subj:
        try:
            sum = s[0]
            if len(s) > 1:
                for t in s[1:]:
                    sum += t
            times.append(sum)
        except Exception:
            sum = datetime.timedelta(0)
            times.append(sum)

    total_time = 0
    str_times = []
    for t in times:
        t = t.total_seconds()
        total_time += t
        hours = round(t // 60)
        minutes = round(t % 60)
        str_times.append(f'{hours}h {minutes}min')

    total_time = f"{round(total_time // 60)}h {round(total_time % 60)}min"
    print(f"\n\n{total_time}\n\n")

    context = {
        "AnNuMa" : str_times[0],
        "Algo1" : str_times[1],
        "PDB" : str_times[2],
        "PPDC" : str_times[3],
        "RTKS" : str_times[4],
        "Kaggle" : str_times[5],
        "edx" : str_times[6],
        "WebProgramming": str_times[7],
        "total_time": total_time
    }
    return render(request, 'datacollection/viewdata.html', context)

datacollection/templates/datacollection/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Timtracking</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'datacollection:enterdata' %}">Insert Data<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'datacollection:viewdata' %}">View Data</a>
            </ul>
        </div>
    </nav>
      {% block body %}
      {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

datacollection/templates/datacollection/enterdata.html
{% extends 'datacollection/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Enter Data
{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <h1>Enter Learning Times</h1>
            <br>
            <form class="forms" action="{% url 'datacollection:enterdata' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-primary" type="submit" value="save">
            </form>
        </div>
    </div>

{% endblock %}

datacollection/templates/datacollection/viewdata.html
{% extends 'datacollection/base.html' %}
{% load static %}

{% block body %}
<br>
<div class="container">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Hours</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>AnNuMa</td>
                    <td>{{ AnNuMa }}</td>
                </tr>
                <tr>
                    <td>Algo1</td>
                    <td>{{ Algo1 }}</td>
                </tr>
                <tr>
                    <td>PDB</td>
                    <td>{{ PDB }}</td>
                </tr>
                <tr>
                    <td>PPDC</td>
                    <td>{{ PPDC }}</td>
                </tr>
                <tr>
                    <td>RTKS</td>
                    <td>{{ RTKS }}</td>
                </tr>
                <tr>
                    <td>Kaggle</td>
                    <td>{{ Kaggle }}</td>
                </tr>
                <tr>
                    <td>edx</td>
                    <td>{{ edx }}</td>
                </tr>
                <tr>
                    <td>Web Programming</td>
                    <td>{{ WebProgramming }}</td>
                </tr>
                <tr>
                    <td><b>Total Time Spend</b></td>
                    <td><b>{{ total_time }}</b></td>
                </tr>
            </tbody>
        </table>

</div>
{% endblock %}